name: Continuous Deployment into AWS ECS
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch'
        required: true
      side:
        description: 'Front or Back'
        required: true
      tag:
        description: 'Image Tag'
        required: true
      short_sha:
        description: 'Short SHA'
        required: true
      

env:
  AWS_REGION: ap-northeast-2                   
  ECR_REPOSITORY: 25_blackout-toowoomba-repository               
  CONTAINER_NAME: 25_blackout-toowoomba-${{ github.event.inputs.target_branch }}-${{ github.event.inputs.side }}-${{ github.event.inputs.short_sha }}
  ECS_SERVICE: 25_blackout-toowoomba-${{ github.event.inputs.target_branch }}-${{ github.event.inputs.side }}-service
  ECS_CLUSTER: 25_blackout-toowoomba-cluster
  # ECS_TASK: ${{ varibales.ECS_TASK_DEF_JSON }}

jobs:
  CD:
    name: CD
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BUILDER_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BUILDER_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true